'use client';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import { sanitizeSummary } from "@/utils/format-utils";

export function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const cleanedSummary = sanitizeSummary(summaryText, 5);
    const summaryContent = `# ${title}\n\nGenerated Summary\n\nGenerated on: ${new Date(createdAt).toLocaleDateString()}\n\n${cleanedSummary}\n\nOriginal File: ${fileName}\nGenerated by Saar-ai\n`;

    const blob = new Blob([summaryContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const sanitizedTitle = title.trim().toLowerCase().replace(/[^a-z0-9]/gi, '_');
    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary-${sanitizedTitle}.txt`;
    // No need to append to DOM
    link.click();
    // Clean up after download
    setTimeout(() => URL.revokeObjectURL(url), 100);
  };

  return (
    <Button
      size="sm"
      className="h-7 sm:h-8 px-2 sm:px-3 bg-lime-100 text-lime-600 hover:text-lime-700 hover:bg-yellow-100 text-xs sm:text-sm rounded-lg sm:rounded-xl transition-all duration-200"
      onClick={handleDownload}
    >
      <Download className="h-3 w-3 sm:h-4 sm:w-4 mr-1 flex-shrink-0" />
      <span className="hidden xs:inline">Download Summary</span>
      <span className="xs:hidden">Download</span>
    </Button>
  );
}